Sprint 2
EvgenyGH/java-filmorate pull request #12
Opened 2022-05-21 15:54 UTC by EvgenyGH

2022-05-21 22:32 UTC, kukolev requested changes

2022-05-21 22:32 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        log.trace(String.format("%-40s - %s", "Добавлен фильм", film));
При логировании лучше использовать возможности библиотеки и пользоваться плейсхолдерами `{}` вместо конкатенации строк. Лучше так: `log.warn("Some warning text for {}", val)` вместо `log.warn("Some warning text for " + val)`. Так код смотрится проще и не происходит лишняя конкатенация строк, если лог не будет напечатан.

2022-05-22 13:22 UTC, EvgenyGH commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        log.trace(String.format("%-40s - %s", "Добавлен фильм", film));
Спасибо! Исправлено.

2022-05-22 16:52 UTC, kukolev approved these changes

2022-05-22 17:30 UTC, merged